### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/exode#7]
Petit bug avec tes modifs @Arias800 

![Capture](https://user-images.githubusercontent.com/4380112/61183481-36dcc080-a642-11e9-8acf-1e2b8f3aa214.PNG)

- l'image ne ce redimention quand largeur.
- le texte ne commence pas au debut.

**Comment by Arias800** [comment]
Ah effectivement faut que j'y jette un oeil ^^

**Comment by Arias800** [comment]
Normalement c'est bon c'est corriger ici : https://github.com/LordVenom/exode/commit/7c78dca482e3a0317ea3c142677dc265578d2a06
